# Generated by Django 4.1 on 2023-04-02 07:30

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtranslation',
            name='additional_headers',
            field=models.CharField(default='Reply-To: ', max_length=255, verbose_name='Additional headers'),
        ),
        migrations.AlterField(
            model_name='mailtranslation',
            name='message_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='From:', verbose_name='Message body'),
        ),
    ]
