# Generated by Django 4.1 on 2023-04-02 07:34

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_mailtranslation_additional_headers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='mailtranslation',
            name='message_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='<p>From: [your-name] &lt;[your-email]&gt;</p><p>Subject: [your-subject]</p><p>Message Body: [your-message]</p><p>-- This e-mail was sent from a contact form on [_site_title] ([_site_url])</p>', verbose_name='Message body'),
        ),
    ]
