# Generated by Django 4.1 on 2023-04-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetranslation',
            name='mail_sent_ng',
            field=models.CharField(default='There was an error trying to send your message. Please try again later.', max_length=255, verbose_name="Sender's message failed to send"),
        ),
        migrations.AlterField(
            model_name='messagetranslation',
            name='validation_error',
            field=models.CharField(default='One or more fields have an error. Please check and try again.', max_length=255, verbose_name='Validation errors occurred'),
        ),
    ]
