# Generated by Django 4.1 on 2023-04-02 08:02

import ckeditor_uploader.fields
import contacts.models
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import parler.fields
import parler.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_rename_contact_contactform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, default='', max_length=128, region=None, verbose_name='phone')),
                ('city', models.CharField(blank=True, max_length=256)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('avatar', models.ImageField(upload_to=contacts.models.user_directory_path, verbose_name='avatar')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contacts.groups')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='GroupsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='content')),
                ('order', models.IntegerField(default=0, null=True, verbose_name='order')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='contacts.groups')),
            ],
            options={
                'verbose_name': 'groups Translation',
                'db_table': 'contacts_groups_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
