# Generated by Django 4.1 on 2023-04-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_groups_contact_groupstranslation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='GroupsTranslation',
            new_name='GroupTranslation',
        ),
        migrations.AlterModelOptions(
            name='grouptranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'group Translation'},
        ),
        migrations.AlterModelTable(
            name='grouptranslation',
            table='contacts_group_translation',
        ),
    ]
