# Generated by Django 4.1 on 2023-04-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_rename_groups_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='grouptranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Group Translation'},
        ),
        migrations.RemoveField(
            model_name='grouptranslation',
            name='content',
        ),
        migrations.RemoveField(
            model_name='grouptranslation',
            name='order',
        ),
    ]
