# Generated by Django 4.2.1 on 2023-07-25 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0010_alter_contact_avatar_alter_contact_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING, to="contacts.group"
            ),
        ),
        migrations.AlterField(
            model_name="mail",
            name="contact_form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="contacts.contactform",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="contact_form",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="contacts.contactform",
            ),
        ),
    ]
