# Generated by Django 4.2.1 on 2023-08-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="content",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="content",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventobject",
            name="content",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
