# Generated by Django 4.2.1 on 2023-08-07 09:17

from django.db import migrations, models
import django.utils.timezone
import events.models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_calendar_content_alter_event_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventobject",
            name="type",
            field=models.CharField(
                choices=[("default", "Default"), ("custom", "Custom")],
                default=django.utils.timezone.now,
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="calendar",
            name="content",
            field=models.JSONField(
                blank=True,
                default=events.models.Calendar.default_calendar_settings,
                null=True,
            ),
        ),
    ]
