# Generated by Django 4.2.1 on 2023-08-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_eventobject_type_alter_calendar_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventobject",
            name="title",
        ),
        migrations.AlterField(
            model_name="eventobject",
            name="type",
            field=models.CharField(
                choices=[("default", "Default"), ("custom", "Custom")],
                default=("default", "Default"),
                max_length=10,
            ),
        ),
    ]
