# Generated by Django 4.2.4 on 2023-12-14 03:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fields", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="field",
            name="fields_fiel_content_5c3519_idx",
        ),
        migrations.RemoveIndex(
            model_name="group",
            name="fields_grou_content_698588_idx",
        ),
        migrations.RemoveField(
            model_name="field",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="field",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="group",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="group",
            name="object_id",
        ),
    ]
