# Generated by Django 4.2.4 on 2023-12-14 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_alter_page_image_alter_page_media"),
        ("fields", "0002_remove_field_fields_fiel_content_5c3519_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="page",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="pages.page",
            ),
        ),
    ]
