# Generated by Django 4.2.1 on 2023-07-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fields", "0002_alter_field_image_alter_group_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldtranslation",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                max_length=255,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="grouptranslation",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                max_length=255,
                unique=True,
                verbose_name="slug",
            ),
        ),
    ]
