# Generated by Django 4.2.1 on 2023-07-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fields", "0003_alter_fieldtranslation_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="group",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
