# Generated by Django 4.2.4 on 2023-12-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_alter_articlecategory_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="%(class)s/", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="media",
            field=models.FileField(
                blank=True, null=True, upload_to="%(class)s/", verbose_name="media"
            ),
        ),
        migrations.AlterField(
            model_name="articlecategory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="%(class)s/", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="articlecategory",
            name="media",
            field=models.FileField(
                blank=True, null=True, upload_to="%(class)s/", verbose_name="media"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="%(class)s/", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="media",
            field=models.FileField(
                blank=True, null=True, upload_to="%(class)s/", verbose_name="media"
            ),
        ),
    ]
