# Generated by Django 4.2.4 on 2023-12-13 05:40

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("plans", "0001_initial"),
        ("testpreps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planitem",
            name="testpreps",
            field=models.ManyToManyField(blank=True, to="testpreps.testprep"),
        ),
        migrations.AddField(
            model_name="optiontranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="plans.option",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plantranslation",
            unique_together={("language_code", "master")},
        ),
        migrations.AlterUniqueTogether(
            name="optiontranslation",
            unique_together={("language_code", "master")},
        ),
    ]
