# Generated by Django 4.2.4 on 2023-12-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testpreps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testprepitemresult",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=14,
            ),
        ),
    ]
