# Generated by Django 4.2.4 on 2023-12-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testpreps", "0003_remove_testprepresult_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testprepresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("in-progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="created",
                max_length=14,
            ),
        ),
    ]
