# Generated by Django 4.2.4 on 2023-12-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testpreps", "0004_alter_testprepresult_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testprepitemresult",
            name="status",
            field=models.CharField(
                choices=[("in-process", "In Process"), ("completed", "Completed")],
                default="in-process",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="testprepresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("initialized", "Initialized"),
                    ("in-progress", "In Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="initialized",
                max_length=14,
            ),
        ),
    ]
