# Generated by Django 4.2.4 on 2023-12-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testpreps", "0006_alter_testprepitemresult_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="testprep",
            name="time",
            field=models.DurationField(default=0),
        ),
    ]
