# Generated by Django 4.2.1 on 2023-09-13 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billings", "0001_initial"),
        ("plans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="billingitem",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="plans.plan"
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
