# Generated by Django 4.2.4 on 2023-12-14 06:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "notification",
            "0002_alter_notification_image_alter_notification_media_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.models.upload_to,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="media",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.models.upload_to,
                verbose_name="media",
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.models.upload_to,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="media",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.models.upload_to,
                verbose_name="media",
            ),
        ),
    ]
