# Generated by Django 4.1 on 2023-04-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
