# Generated by Django 4.1 on 2023-04-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_gallery_status_alter_group_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20),
        ),
    ]
