# Generated by Django 4.1 on 2023-04-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_alter_gallery_status_alter_group_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerytranslation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='grouptranslation',
            name='order',
        ),
        migrations.RemoveField(
            model_name='imagetranslation',
            name='order',
        ),
        migrations.AddField(
            model_name='gallerytranslation',
            name='position',
            field=models.IntegerField(default=0, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='grouptranslation',
            name='position',
            field=models.IntegerField(default=0, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='imagetranslation',
            name='position',
            field=models.IntegerField(default=0, null=True, verbose_name='Position'),
        ),
    ]
