# Generated by Django 4.2.1 on 2023-07-25 04:32

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0005_alter_gallery_image_alter_group_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="children",
                to="albums.group",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="gallery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="gallery_images",
                to="albums.gallery",
            ),
        ),
    ]
