# Generated by Django 4.2.1 on 2023-08-16 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0008_alter_gallery_status_alter_group_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
