# Generated by Django 4.2.1 on 2023-08-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0009_alter_gallery_id_alter_group_id_alter_image_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
