# Generated by Django 4.2.1 on 2023-08-16 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("albums", "0011_gallery_uuid_group_uuid_image_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="uuid",
            field=models.UUIDField(
                auto_created=True, default=uuid.uuid4, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="uuid",
            field=models.UUIDField(
                auto_created=True, default=uuid.uuid4, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="uuid",
            field=models.UUIDField(
                auto_created=True, default=uuid.uuid4, editable=False
            ),
        ),
    ]
