# Generated by Django 4.2.4 on 2023-12-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="language",
            field=models.CharField(
                choices=[("en", "EN"), ("ar", "AR")],
                default="en_US",
                max_length=5,
                verbose_name="language",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="language",
            field=models.CharField(
                choices=[("en", "EN"), ("ar", "AR")],
                default="en_US",
                max_length=5,
                verbose_name="language",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="language",
            field=models.CharField(
                choices=[("en", "EN"), ("ar", "AR")],
                default="en_US",
                max_length=5,
                verbose_name="language",
            ),
        ),
    ]
