# Generated by Django 4.2.1 on 2023-08-30 03:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import settings.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="files/")),
            ],
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, upload_to="files/")),
                ("image", models.ImageField(blank=True, upload_to="files/")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("textarea", "TextArea"),
                            ("richtext", "RichText"),
                            ("file", "File"),
                            ("gallery", "Gallery"),
                            ("url", "Url"),
                        ],
                        default=("text", "Text"),
                        max_length=16,
                    ),
                ),
                (
                    "image_picker",
                    settings.fields.ImagePickerField(
                        on_delete=django.db.models.deletion.CASCADE, to="settings.image"
                    ),
                ),
            ],
            options={
                "verbose_name": "Setting",
                "verbose_name_plural": "Settings",
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SettingTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=255,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                ("text", models.CharField(blank=True, max_length=255)),
                ("textarea", models.TextField(blank=True)),
                ("richtext", ckeditor.fields.RichTextField(blank=True)),
                ("url", models.URLField(blank=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="settings.setting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Setting Translation",
                "db_table": "settings_setting_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
