# Generated by Django 4.2.1 on 2023-08-30 04:05

from django.db import migrations
import django.db.models.deletion
import settings.fields


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="image_picker",
            field=settings.fields.ImagePickerField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.image",
            ),
        ),
    ]
