# Generated by Django 4.2.1 on 2023-08-30 04:25

from django.db import migrations, models
import django.db.models.deletion
import settings.fields


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_alter_setting_image_picker"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, upload_to="files/")),
            ],
        ),
        migrations.AlterField(
            model_name="setting",
            name="image_picker",
            field=settings.fields.ImagePickerField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="settings.file",
            ),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
