# Generated by Django 4.2.1 on 2023-08-30 07:08

from django.db import migrations
import django.db.models.deletion
import settings.fields


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_file_alter_setting_image_picker_delete_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="image_picker_multiple",
            field=settings.fields.ImagePickerMultipleField(
                related_name="image_picker_multiple", to="settings.file"
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="image_picker",
            field=settings.fields.ImagePickerField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_picker",
                to="settings.file",
            ),
        ),
    ]
