# Generated by Django 4.2.1 on 2023-08-30 11:43

from django.db import migrations
import django.db.models.deletion
import settings.fields


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0004_setting_image_picker_multiple_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setting",
            name="image_picker_multiple",
        ),
        migrations.AlterField(
            model_name="setting",
            name="image_picker",
            field=settings.fields.ImagePickerField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="image_picker",
                to="settings.file",
            ),
        ),
    ]
