# Generated by Django 4.2.1 on 2023-08-30 14:08

from django.db import migrations
import settings.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "settings",
            "0006_alter_file_options_file__file_size_file_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="setting",
            name="image_picker_multiple",
            field=settings.fields.ImagePickerMultipleField(
                blank=True,
                null=True,
                related_name="image_picker_multiple",
                to="settings.file",
            ),
        ),
    ]
