# Generated by Django 4.2.1 on 2023-09-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0008_remove_setting_image_picker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("textarea", "TextArea"),
                    ("richtext", "RichText"),
                    ("image", "Image"),
                    ("file", "File"),
                    ("gallery", "Gallery"),
                    ("url", "Url"),
                ],
                default=("text", "Text"),
                max_length=16,
            ),
        ),
    ]
