# Generated by Django 4.2.4 on 2023-11-27 07:15

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0003_question_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="title",
        ),
        migrations.AddField(
            model_name="answer",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="content"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="content"
            ),
        ),
    ]
