# Generated by Django 4.2.4 on 2023-12-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0005_quiz_answers_at_end_quiz_description_quiz_draft_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(
                blank=True,
                help_text="Explanation to be shown after the question has been answered.",
                max_length=2000,
                verbose_name="Explanation",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="figure",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uploads/%Y/%m/%d",
                verbose_name="Figure",
            ),
        ),
    ]
