# Generated by Django 4.2.4 on 2023-12-13 05:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0008_quiz_created_at_quiz_created_by_quiz_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name": "Quizz", "verbose_name_plural": "Quizzes"},
        ),
    ]
