# Generated by Django 4.2.4 on 2023-12-18 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0009_alter_quiz_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="questions",
                to="quizzes.quiz",
            ),
        ),
    ]
