# Generated by Django 4.2.4 on 2023-12-25 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0010_alter_question_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="uploads/%Y/%m/%d",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="answers",
                to="quizzes.question",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="url",
            field=models.SlugField(
                blank=True,
                help_text="a user friendly url",
                max_length=60,
                verbose_name="user friendly url",
            ),
        ),
    ]
