# Generated by Django 4.2.1 on 2023-07-25 04:08

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("unconfirmed", "Unconfirmed"),
                            ("unfulfilled", "Unfulfilled"),
                            ("partially fulfilled", "Partially fulfilled"),
                            ("partially_returned", "Partially returned"),
                            ("returned", "Returned"),
                            ("fulfilled", "Fulfilled"),
                            ("canceled", "Canceled"),
                        ],
                        default="unfulfilled",
                        max_length=32,
                    ),
                ),
                (
                    "authorize_status",
                    models.CharField(
                        choices=[
                            ("none", "The funds are not authorized"),
                            (
                                "partial",
                                "The funds that are authorized or charged don't cover fully the order's total",
                            ),
                            (
                                "full",
                                "The funds that are authorized or charged fully cover the order's total",
                            ),
                        ],
                        db_index=True,
                        default="none",
                        max_length=32,
                    ),
                ),
                (
                    "charge_status",
                    models.CharField(
                        choices=[
                            ("none", "The funds are not charged."),
                            (
                                "partial",
                                "The funds that are charged, don't cover the order's total",
                            ),
                            (
                                "full",
                                "The funds that are charged fully cover the order's total",
                            ),
                            (
                                "overcharged",
                                "The charged funds are bigger than order's total",
                            ),
                        ],
                        db_index=True,
                        default="none",
                        max_length=32,
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[("en", "English"), ("ar", "العربيّة")],
                        default="en",
                        max_length=35,
                    ),
                ),
                (
                    "tracking_client_id",
                    models.CharField(blank=True, editable=False, max_length=36),
                ),
                (
                    "user_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("checkout", "Checkout"),
                            ("draft", "Draft"),
                            ("reissue", "Reissue"),
                        ],
                        max_length=32,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("checkout_token", models.CharField(blank=True, max_length=36)),
                (
                    "total_net_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                (
                    "undiscounted_total_net_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                (
                    "total_gross_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                (
                    "undiscounted_total_gross_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                (
                    "total_charged_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                (
                    "total_authorized_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                ("display_gross_prices", models.BooleanField(default=True)),
                ("customer_note", models.TextField(blank=True, default="")),
                ("redirect_url", models.URLField(blank=True, null=True)),
                ("search_document", models.TextField(blank=True, default="")),
                ("should_refresh_prices", models.BooleanField(default=True)),
                ("tax_exemption", models.BooleanField(default=False)),
                (
                    "billing_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.address",
                    ),
                ),
                (
                    "original",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.order",
                    ),
                ),
                (
                    "shipping_address",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.address",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("product_name", models.CharField(max_length=386)),
                (
                    "variant_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "product_sku",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_variant_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_shipping_required", models.BooleanField(default=False)),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "quantity_fulfilled",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "unit_discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                ("unit_discount_reason", models.TextField(blank=True, null=True)),
                (
                    "unit_price_net_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                (
                    "unit_discount_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                (
                    "unit_price_gross_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "total_price_net_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                (
                    "total_price_gross_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "undiscounted_unit_price_gross_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                (
                    "undiscounted_unit_price_net_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                (
                    "undiscounted_total_price_gross_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                (
                    "undiscounted_total_price_net_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                (
                    "base_unit_price_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                (
                    "undiscounted_base_unit_price_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.0"), max_digits=12
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="orders.order",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_lines",
                        to="products.plan",
                    ),
                ),
            ],
            options={
                "ordering": ("created_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DRAFT_CREATED", "draft_created"),
                            (
                                "DRAFT_CREATED_FROM_REPLACE",
                                "draft_created_from_replace",
                            ),
                            ("ADDED_PRODUCTS", "added_products"),
                            ("REMOVED_PRODUCTS", "removed_products"),
                            ("PLACED", "placed"),
                            ("PLACED_FROM_DRAFT", "placed_from_draft"),
                            ("OVERSOLD_ITEMS", "oversold_items"),
                            ("CANCELED", "canceled"),
                            ("ORDER_MARKED_AS_PAID", "order_marked_as_paid"),
                            ("ORDER_FULLY_PAID", "order_fully_paid"),
                            ("ORDER_REPLACEMENT_CREATED", "order_replacement_created"),
                            ("ORDER_DISCOUNT_ADDED", "order_discount_added"),
                            (
                                "ORDER_DISCOUNT_AUTOMATICALLY_UPDATED",
                                "order_discount_automatically_updated",
                            ),
                            ("ORDER_DISCOUNT_UPDATED", "order_discount_updated"),
                            ("ORDER_DISCOUNT_DELETED", "order_discount_deleted"),
                            (
                                "ORDER_LINE_DISCOUNT_UPDATED",
                                "order_line_discount_updated",
                            ),
                            (
                                "ORDER_LINE_DISCOUNT_REMOVED",
                                "order_line_discount_removed",
                            ),
                            (
                                "ORDER_LINE_PRODUCT_DELETED",
                                "order_line_product_deleted",
                            ),
                            (
                                "ORDER_LINE_VARIANT_DELETED",
                                "order_line_variant_deleted",
                            ),
                            ("UPDATED_ADDRESS", "updated_address"),
                            ("EMAIL_SENT", "email_sent"),
                            ("CONFIRMED", "confirmed"),
                            ("PAYMENT_AUTHORIZED", "payment_authorized"),
                            ("PAYMENT_CAPTURED", "payment_captured"),
                            (
                                "EXTERNAL_SERVICE_NOTIFICATION",
                                "external_service_notification",
                            ),
                            ("PAYMENT_REFUNDED", "payment_refunded"),
                            ("PAYMENT_VOIDED", "payment_voided"),
                            ("PAYMENT_FAILED", "payment_failed"),
                            ("TRANSACTION_EVENT", "transaction_event"),
                            (
                                "TRANSACTION_CAPTURE_REQUESTED",
                                "transaction_capture_requested",
                            ),
                            (
                                "TRANSACTION_REFUND_REQUESTED",
                                "transaction_refund_requested",
                            ),
                            (
                                "TRANSACTION_VOID_REQUESTED",
                                "transaction_void_requested",
                            ),
                            ("INVOICE_REQUESTED", "invoice_requested"),
                            ("INVOICE_GENERATED", "invoice_generated"),
                            ("INVOICE_UPDATED", "invoice_updated"),
                            ("INVOICE_SENT", "invoice_sent"),
                            ("FULFILLMENT_CANCELED", "fulfillment_canceled"),
                            (
                                "FULFILLMENT_RESTOCKED_ITEMS",
                                "fulfillment_restocked_items",
                            ),
                            (
                                "FULFILLMENT_FULFILLED_ITEMS",
                                "fulfillment_fulfilled_items",
                            ),
                            ("FULFILLMENT_REFUNDED", "fulfillment_refunded"),
                            ("FULFILLMENT_RETURNED", "fulfillment_returned"),
                            ("FULFILLMENT_REPLACED", "fulfillment_replaced"),
                            (
                                "FULFILLMENT_AWAITS_APPROVAL",
                                "fulfillment_awaits_approval",
                            ),
                            ("TRACKING_UPDATED", "tracking_updated"),
                            ("NOTE_ADDED", "note_added"),
                            ("OTHER", "other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("date",),
            },
        ),
    ]
