# Generated by Django 4.2.4 on 2023-12-13 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("lessons", "0002_lesson_create_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="create_by",
        ),
        migrations.AddField(
            model_name="lesson",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_by",
                to="accounts.teacher",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updated_by",
                to="accounts.teacher",
            ),
        ),
    ]
