# Generated by Django 4.2.4 on 2023-12-13 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
        ("lessons", "0004_lesson_created_at_lesson_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_created_by",
                to="accounts.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="updated_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_updated_by",
                to="accounts.teacher",
            ),
        ),
    ]
