# Generated by Django 4.2.4 on 2023-12-13 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0005_alter_lesson_created_by_alter_lesson_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcript",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="%(class)s/", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="transcript",
            name="media",
            field=models.FileField(
                blank=True, null=True, upload_to="%(class)s/", verbose_name="media"
            ),
        ),
    ]
