# Generated by Django 4.2.4 on 2023-12-14 06:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0006_alter_transcript_image_alter_transcript_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcript",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=core.models.upload_to,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="transcript",
            name="media",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=core.models.upload_to,
                verbose_name="media",
            ),
        ),
    ]
